import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import {
  Check,
  FileText,
  Factory,
  Globe,
  History,
  Image,
  Loader2,
  ShieldCheck,
  Sparkles,
  Tags,
  type LucideIcon,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { duration } from "@/lib/format";
import { cn } from "@/lib/utils";

interface Stage {
  key: string;
  title: string;
  detail: string;
  icon: LucideIcon;
  model: "none" | "picks" | "extracts" | "writes" | "retrieves" | "replays";
}

/**
 * The eight stages, in order, with an honest note on what the model is allowed
 * to do in each. Four of the eight never call a model at all, which is the
 * point: generation is constrained by lookups and retrieval rather than trusted
 * to behave. Keys match the backend's STAGES exactly — the live stream sends
 * these names as each agent starts and finishes.
 */
export const STAGES: Stage[] = [
  {
    key: "classifier",
    title: "Classify",
    detail:
      "Category triple narrows 62 classpaths to a shortlist. A near-duplicate labelled row decides it outright; otherwise the model picks from the shortlist.",
    icon: Tags,
    model: "picks",
  },
  {
    key: "manufacturer_resolver",
    title: "Resolve brand",
    detail:
      "Brand hints, then part-number prefix, then description shorthand. A buying co-op supplier string is ignored, because it fronts six unrelated brands.",
    icon: Factory,
    model: "picks",
  },
  {
    key: "research",
    title: "Research sources",
    detail:
      "Finds and reads first-party documents — datasheets and product pages from the manufacturer's own site — and verifies they name this part number.",
    icon: Globe,
    model: "retrieves",
  },
  {
    key: "attribute_extractor",
    title: "Extract attributes",
    detail:
      "The classpath template fixes which attributes exist and in what order. Values verified verbatim against a retrieved source are marked grounded.",
    icon: Sparkles,
    model: "extracts",
  },
  {
    key: "description_builder",
    title: "Build descriptions",
    detail:
      "Five surfaces assembled by a grammar mined from labelled rows. Values come only from attributes that already passed validation.",
    icon: FileText,
    model: "writes",
  },
  {
    key: "sourcing",
    title: "Assets & sourcing",
    detail:
      "Asset filenames from the house naming convention, plus the approved manufacturer domain. Fully deterministic — no model call.",
    icon: Image,
    model: "none",
  },
  {
    key: "validator",
    title: "Validate & score",
    detail:
      "Character limits, casing, unit spacing, fractions and vocabulary membership. Assigns per-field confidence and the needs-review flag.",
    icon: ShieldCheck,
    model: "none",
  },
  {
    key: "corrections",
    title: "Replay decisions",
    detail:
      "Reviewer approvals and overrides replay last, so a corrected value is final and never regenerated by a later run.",
    icon: History,
    model: "replays",
  },
];

const MODEL_BADGE: Record<
  Stage["model"],
  { text: string; variant: "outline" | "primary" | "success" }
> = {
  none: { text: "Deterministic", variant: "outline" },
  picks: { text: "Model picks", variant: "primary" },
  extracts: { text: "Model extracts", variant: "primary" },
  writes: { text: "Formula", variant: "outline" },
  retrieves: { text: "Web retrieval", variant: "success" },
  replays: { text: "Human memory", variant: "outline" },
};

export type StageStatus = "idle" | "active" | "done";

/** Live per-stage state, keyed by stage key, driven by the SSE stream. */
export interface StageState {
  status: StageStatus;
  elapsedMs?: number;
}

/**
 * Wall-clock ticker that only runs while a stage is active, so the elapsed
 * readout counts up live. The stream reports elapsed only when a stage ends;
 * between `start` and `end` we own the number.
 */
function useNow(active: boolean): number {
  const [now, setNow] = useState(() => performance.now());
  useEffect(() => {
    if (!active) return;
    const id = window.setInterval(() => setNow(performance.now()), 120);
    return () => window.clearInterval(id);
  }, [active]);
  return now;
}

export function PipelineFlow({
  status = "idle",
  activeIndex = -1,
  stageStates,
}: {
  status?: StageStatus;
  activeIndex?: number;
  /** Real per-stage state from the stream; overrides the index-based walk. */
  stageStates?: Record<string, StageState>;
}) {
  const anyActive = stageStates
    ? Object.values(stageStates).some((s) => s.status === "active")
    : status === "active";
  const doneCount = stageStates
    ? Object.values(stageStates).filter((s) => s.status === "done").length
    : status === "done"
      ? STAGES.length
      : Math.max(activeIndex, 0);

  // When a stage flips to active, remember when we first saw it so the live
  // elapsed readout has a start point. Cleared when it finishes.
  const starts = useRef(new Map<string, number>());
  if (stageStates) {
    for (const [key, state] of Object.entries(stageStates)) {
      if (state.status === "active" && !starts.current.has(key)) {
        starts.current.set(key, performance.now());
      } else if (state.status !== "active") {
        starts.current.delete(key);
      }
    }
  }
  const now = useNow(anyActive);

  return (
    <div>
      <div className="mb-3 flex items-center justify-between gap-2">
        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          {STAGES.length} agents · {doneCount} complete
        </p>
        {anyActive ? (
          <span className="flex items-center gap-1.5 text-xs font-medium text-primary">
            <span className="relative flex size-1.5" aria-hidden>
              <span className="absolute inline-flex size-full animate-ping rounded-full bg-primary opacity-70" />
              <span className="relative inline-flex size-1.5 rounded-full bg-primary" />
            </span>
            Live
          </span>
        ) : null}
      </div>

      {/*
       * A timeline rather than a stack of cards: one continuous rail down the
       * icon column, segmented per stage and coloured by that stage's state,
       * so progress reads as a single flow from top to bottom.
       */}
      <ol className="relative" aria-label="Enrichment pipeline stages">
        {STAGES.map((stage, index) => {
          const live = stageStates?.[stage.key];
          const isDone = live
            ? live.status === "done"
            : status === "done" || (status === "active" && index < activeIndex);
          const isActive = live
            ? live.status === "active"
            : status === "active" && index === activeIndex;
          const badge = MODEL_BADGE[stage.model];
          const startedAt = starts.current.get(stage.key);
          const elapsedLabel =
            live?.status === "done" && live.elapsedMs !== undefined
              ? duration(live.elapsedMs)
              : isActive && startedAt !== undefined
                ? duration(now - startedAt)
                : null;

          return (
            <motion.li
              key={stage.key}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, delay: index * 0.05 }}
              className="group relative flex gap-3.5 rounded-lg p-2.5 transition-colors duration-300 hover:bg-surface/70"
            >
              {/* Rail segment: from this node's centre to the item's end. */}
              {index < STAGES.length - 1 ? (
                <span
                  aria-hidden
                  className={cn(
                    "absolute bottom-0 left-[1.4375rem] top-[calc(0.625rem+1.75rem)] w-px transition-colors duration-500",
                    isDone
                      ? "bg-success/50"
                      : isActive
                        ? "bg-gradient-to-b from-primary/70 to-primary/20"
                        : "bg-border",
                  )}
                />
              ) : null}

              <div
                className={cn(
                  "relative z-10 mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-md border backdrop-blur-sm transition-colors duration-300",
                  isDone
                    ? "border-success/40 bg-success/15 text-success"
                    : isActive
                      ? "animate-pulse-ring border-primary/50 bg-primary/15 text-primary"
                      : "border-border bg-secondary/80 text-muted-foreground",
                )}
                aria-hidden
              >
                {isDone ? (
                  <Check className="size-3.5" />
                ) : isActive ? (
                  <Loader2 className="size-3.5 animate-spin" />
                ) : (
                  <stage.icon className="size-3.5" />
                )}
              </div>

              <div
                className={cn(
                  "min-w-0 flex-1 space-y-1 rounded-lg border p-3 transition-colors duration-300",
                  isActive
                    ? "border-primary/50 bg-primary/[0.07] shadow-glow"
                    : isDone
                      ? "border-success/25 bg-success/[0.04]"
                      : "border-border/60 bg-surface/40",
                )}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <p className="text-sm font-medium leading-none">
                    <span className="tabular mr-1.5 text-muted-foreground">{index + 1}.</span>
                    {stage.title}
                  </p>
                  <Badge variant={badge.variant} className="text-[0.625rem]">
                    {badge.text}
                  </Badge>
                  {elapsedLabel ? (
                    <span
                      className={cn(
                        "tabular ml-auto text-[0.6875rem]",
                        isActive ? "font-medium text-primary" : "text-muted-foreground",
                      )}
                    >
                      {elapsedLabel}
                    </span>
                  ) : null}
                </div>
                <p className="text-xs leading-relaxed text-muted-foreground">{stage.detail}</p>
              </div>
            </motion.li>
          );
        })}
      </ol>
    </div>
  );
}
