"""Pipeline orchestration.

Sequences the agents per record and runs records concurrently. Each stage is
wrapped so that a failure degrades that one row rather than aborting the batch:
a partially enriched row with an explicit issue is more useful than a crash.
"""

from __future__ import annotations

import logging
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Callable, Iterable, Sequence

import pandas as pd

from backend.config import settings
from backend.core.schema import ProductRecord
from backend.knowledge.corrections import CorrectionStore, get_corrections
from backend.knowledge.datasets import records_from
from backend.knowledge.registry import KnowledgeBase
from backend.llm.client import GeminiClient, get_client
from backend.pipeline.agents.attributes import AttributeAgent
from backend.pipeline.agents.classifier import ClassifierAgent
from backend.pipeline.agents.descriptions import DescriptionAgent
from backend.pipeline.agents.manufacturer import ManufacturerAgent
from backend.pipeline.agents.research import ResearchAgent
from backend.pipeline.agents.sourcing import SourcingAgent
from backend.pipeline.agents.validator import ValidatorAgent
from backend.sourcing.fetch import get_fetcher

logger = logging.getLogger(__name__)

ProgressHook = Callable[[int, int, ProductRecord], None]
# (stage, event, record, elapsed_ms): fired as each stage starts and ends, so
# a UI can light up the agents in real time instead of guessing at progress.
StageHook = Callable[[str, str, ProductRecord, float], None]

STAGES: tuple[str, ...] = (
    "classifier",
    "manufacturer_resolver",
    # Retrieval sits between identity and extraction: it needs a brand to know
    # whose site it may read, and the attribute stage needs its output.
    "research",
    "attribute_extractor",
    "description_builder",
    "sourcing",
    "validator",
    # Human-in-the-loop: reviewer decisions replay last, so a corrected value
    # is final and never regenerated by a later run.
    "corrections",
)


@dataclass
class PipelineResult:
    records: list[ProductRecord] = field(default_factory=list)
    elapsed_seconds: float = 0.0
    usage: dict = field(default_factory=dict)
    stage_failures: dict[str, int] = field(default_factory=dict)
    retrieval: dict = field(default_factory=dict)

    def to_frame(self) -> pd.DataFrame:
        from backend.core.schema import delivery_columns

        rows = [r.to_delivery_row() for r in self.records]
        return pd.DataFrame(rows, columns=delivery_columns())

    @property
    def review_count(self) -> int:
        return sum(1 for r in self.records if r.needs_review)

    @property
    def sourced_count(self) -> int:
        """Records for which at least one first-party document was read."""
        return sum(1 for r in self.records if r.citations)

    def summary(self) -> dict:
        from backend.llm.pricing import estimate_cost

        total = len(self.records) or 1
        confidences = [r.confidence.get("overall", 0.0) for r in self.records]
        grounded = sum(r.grounded_count for r in self.records)
        filled = sum(len(r.filled_attributes()) for r in self.records)
        return {
            "records": len(self.records),
            "elapsed_seconds": round(self.elapsed_seconds, 1),
            "seconds_per_record": round(self.elapsed_seconds / total, 2),
            "needs_review": self.review_count,
            "review_rate": round(self.review_count / total, 3),
            "mean_confidence": round(sum(confidences) / total, 3),
            "total_issues": sum(len(r.issues) for r in self.records),
            "stage_failures": self.stage_failures,
            "llm": self.usage,
            # The business story: what this run cost, and what the cache saved.
            "cost": estimate_cost(self.usage, len(self.records)),
            # Retrieval reach and how much of the output it actually underwrites.
            "sourced_records": self.sourced_count,
            "sourced_rate": round(self.sourced_count / total, 3),
            "documents_read": sum(len(r.citations) for r in self.records),
            "grounded_attributes": grounded,
            "grounded_rate": round(grounded / filled, 3) if filled else 0.0,
            "retrieval": self.retrieval,
        }


def _usage_delta(before: dict, after: dict) -> dict:
    """Attribute only this run's LLM activity, from two gateway snapshots.

    Counters are cumulative across the process, so a naive snapshot would bill
    every earlier run against the current one. The delta keeps the same shape
    as a snapshot so downstream consumers (summary, cost, the UI) are unchanged.
    """
    by_model = {
        model: count - before.get("by_model", {}).get(model, 0)
        for model, count in after.get("by_model", {}).items()
    }
    by_model = {model: count for model, count in by_model.items() if count > 0}
    live = after.get("live_calls", 0) - before.get("live_calls", 0)
    calls = after.get("calls", 0) - before.get("calls", 0)
    cache_hits = after.get("cache_hits", 0) - before.get("cache_hits", 0)
    return {
        "calls": calls,
        "cache_hits": cache_hits,
        "live_calls": live,
        "failures": after.get("failures", 0) - before.get("failures", 0),
        "total_tokens": after.get("total_tokens", 0) - before.get("total_tokens", 0),
        "avg_latency_s": after.get("avg_latency_s", 0.0),
        # This run's rate, not the process-wide one, so a fully cached re-run
        # reports 100% even if earlier runs were live.
        "cache_hit_rate": round(cache_hits / calls, 3) if calls else 0.0,
        "by_model": by_model,
        "exhausted_models": after.get("exhausted_models", []),
    }


class EnrichmentPipeline:
    """Runs the staged enrichment over a batch of raw product rows."""

    def __init__(
        self,
        kb: KnowledgeBase,
        llm: GeminiClient | None = None,
        corrections: CorrectionStore | None = None,
    ) -> None:
        self.kb = kb
        self.llm = llm or get_client()
        # Shared across the process so reviewer decisions persist between runs.
        self.corrections = corrections or get_corrections()
        self.classifier = ClassifierAgent(kb, self.llm)
        self.manufacturer = ManufacturerAgent(kb, self.llm)
        self.research = ResearchAgent(kb)
        self.attributes = AttributeAgent(kb, self.llm)
        self.descriptions = DescriptionAgent(kb, self.llm)
        self.sourcing = SourcingAgent(kb)
        self.validator = ValidatorAgent(kb)
        self._failures: dict[str, int] = {}

    # -- single record --
    def enrich(
        self,
        record: ProductRecord,
        *,
        stage_hook: StageHook | None = None,
    ) -> ProductRecord:
        """Run every stage, isolating failures to the stage that caused them."""
        stages: Sequence[tuple[str, Callable[[ProductRecord], ProductRecord]]] = (
            ("classifier", self.classifier.run),
            ("manufacturer_resolver", self.manufacturer.run),
            ("research", self.research.run),
            ("attribute_extractor", self.attributes.run),
            ("description_builder", self.descriptions.run),
            ("sourcing", self.sourcing.run),
            ("validator", self.validator.run),
            ("corrections", self.corrections.apply),
        )
        for name, run in stages:
            started = time.perf_counter()
            if stage_hook:
                try:
                    stage_hook(name, "start", record, 0.0)
                except Exception:  # noqa: BLE001 - observers never break the run
                    logger.exception("stage hook failed for %s", name)
            try:
                record = run(record)
            except Exception as exc:  # noqa: BLE001 - keep the batch alive
                logger.exception("stage %s failed for %s", name, record.part_number)
                record.issues.append(f"stage {name} failed: {type(exc).__name__}")
                record.needs_review = True
                self._failures[name] = self._failures.get(name, 0) + 1
            if stage_hook:
                try:
                    stage_hook(name, "end", record, (time.perf_counter() - started) * 1000)
                except Exception:  # noqa: BLE001
                    logger.exception("stage hook failed for %s", name)

        # Release the retrieved document text once every stage has read it.
        # Citations, spec tables and grounding decisions are already recorded;
        # keeping whole PDFs for hundreds of records would grow without bound.
        if record.evidence is not None:
            record.evidence.compact()
        return record

    # -- batch --
    def run(
        self,
        records: Iterable[ProductRecord],
        *,
        progress: ProgressHook | None = None,
        max_workers: int | None = None,
        stage_hook: StageHook | None = None,
    ) -> PipelineResult:
        items = list(records)
        total = len(items)
        workers = max_workers or settings.max_concurrency
        started = time.perf_counter()
        self._failures = {}

        # The gateway's counters are process-wide, so snapshot before and after
        # to attribute only this run's calls, tokens and cache hits to it.
        before = self.llm.stats.snapshot()

        # Preserve input order in the output regardless of completion order.
        done: dict[int, ProductRecord] = {}
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = {
                pool.submit(self.enrich, rec, stage_hook=stage_hook): i
                for i, rec in enumerate(items)
            }
            for completed, future in enumerate(as_completed(futures), start=1):
                index = futures[future]
                try:
                    done[index] = future.result()
                except Exception as exc:  # noqa: BLE001
                    logger.exception("record %s crashed", index)
                    fallback = items[index]
                    fallback.issues.append(f"pipeline crashed: {type(exc).__name__}")
                    fallback.needs_review = True
                    done[index] = fallback
                if progress:
                    progress(completed, total, done[index])

        after = self.llm.stats.snapshot()
        usage = _usage_delta(before, after)

        return PipelineResult(
            records=[done[i] for i in range(total)],
            elapsed_seconds=time.perf_counter() - started,
            usage=usage,
            stage_failures=dict(self._failures),
            retrieval=get_fetcher().stats.snapshot(),
        )

    def run_frame(
        self, frame: pd.DataFrame, *, progress: ProgressHook | None = None
    ) -> PipelineResult:
        """Convenience wrapper for a raw input DataFrame."""
        return self.run(records_from(frame), progress=progress)
